language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

git:
    submodules: false

before_script:
    - composer require phpspec/phpspec:~2.0 --no-update
    - composer install

script:
    - ./vendor/bin/phpspec run -fpretty
    - phpunit
