language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: 7.0

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

git:
    submodules: false

before_script:
    - composer require phpspec/phpspec:~2.0 --no-update
    - composer update

script:
    - ./vendor/bin/phpspec run -fpretty
    - phpunit
