language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - PIMPLE=no
    - PIMPLE=yes

before_script:
    - if [[ "$PIMPLE" == 1 ]]; then echo "PIMPLE C EXTENSION"; fi
    - composer require phpspec/phpspec:~2.0 --no-update
    - composer install

script:
    - phpunit
    - ./vendor/bin/phpspec run -fpretty
