language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - PIMPLE=no
    - PIMPLE=yes

git:
    submodules: false

before_script:
    - composer require phpspec/phpspec:~2.0 --no-update
    - composer install
    - if [[ "$PIMPLE" == "yes" ]]; then cd vendor/pimple/pimple/ext/pimple; phpize; ./configure; make install; cd $TRAVIS_BUILD_DIR; fi
    - if [[ "$PIMPLE" == "yes" ]]; then echo "extension=pimple.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/pimple.ini; fi

script:
    - phpunit
    - ./vendor/bin/phpspec run -fpretty
