language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

git:
    submodules: false

before_script:
    - composer require phpspec/phpspec:~2.0 --no-update
    - composer install

script:
    - ./vendor/bin/phpspec run -fpretty
    - phpunit
