language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - "composer require phpspec/phpspec:~2.0 --no-update"
    - "composer install"

script:
    - phpunit
    - ./vendor/bin/phpspec run -fpretty
